env:
  repo: you54f/traveling-ruby
  NEXT_TAG: rel-20230529-next
#   GITHUB_TOKEN: ENCRYPTED[7f3663f35400d0e1f8e0fec456af6b75a07b0fd2d0632fe1697b8fb73af5e78245144216288d88d2daa681ccd159e07d]

RUBY_VERSIONS_TASKS: &RUBY_VERSIONS_TASKS
  - script: rake package:$ARCHITECTURES:3.3.0-preview1
    test: rake testdocker:$ARCHITECTURES:3.3.0-preview1
# failed on docker mani entry



  # - script: rake package:$ARCHITECTURES:3.2.2
  #   test: rake testdocker:$ARCHITECTURES:3.2.2
# 3.2.2
# | PLATFORM | ARCH   | Working |
# | OSX     | x86_64 |  |
# | OSX     | arm64  |  |
# | Linux   | x86_64 |  |
# | Linux   | arm64  | ✅ |
# | Windows | x86_64 |  |
# | Windows | x86    |  |

  # - script: rake package:$ARCHITECTURES:3.1.4
  #   test: rake testdocker:$ARCHITECTURES:3.1.4

# 3.1.4
# | PLATFORM | ARCH   | Working |
# | OSX     | x86_64 |  |
# | OSX     | arm64  |  |
# | Linux   | x86_64 |  |
# | Linux   | arm64  | X |
# | Windows | x86_64 |  |
# | Windows | x86    |  |


  # - script: rake package:$ARCHITECTURES:3.1.2
  #   test: rake testdocker:$ARCHITECTURES:3.1.2
# 3.1.2
# | PLATFORM | ARCH   | Working |
# | OSX     | x86_64 |  |
# | OSX     | arm64  |  |
# | Linux   | x86_64 |  |
# | Linux   | arm64  | ✅ |
# | Windows | x86_64 |  |
# | Windows | x86    |  |


  # - script: rake package:$ARCHITECTURES:3.0.6
  #   test: rake testdocker:$ARCHITECTURES:3.0.6
# + /tmp/ruby/bin/gem install bundler -v 2.4.10 --no-document
# ERROR:  While executing gem ... (Gem::Exception)
#     OpenSSL is not available. Install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources
# rake aborted!

# 3.0.6
# | PLATFORM | ARCH   | Working |
# | OSX     | x86_64 |  |
# | OSX     | arm64  |  |
# | Linux   | x86_64 |  |
# | Linux   | arm64  | X |
# | Windows | x86_64 |  |
# | Windows | x86    |  |

  # - script: rake package:$ARCHITECTURES:3.0.4
  #   test: rake testdocker:$ARCHITECTURES:3.0.4

# 3.0.4
# | PLATFORM | ARCH   | Working |
# | OSX     | x86_64 |  |
# | OSX     | arm64  |  |
# | Linux   | x86_64 |  |
# | Linux   | arm64  | ✅ |
# | Windows | x86_64 |  |
# | Windows | x86    |  |

  # - script: rake package:$ARCHITECTURES:2.7.8
  #   test: rake testdocker:$ARCHITECTURES:2.7.8
# /tmp/ruby-2.7.8/lib/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- openssl (LoadError)
#         from /tmp/ruby-2.7.8/lib/rubygems/core_ext/kernel_require.rb:83:in `require'
#   - script: rake package:$ARCHITECTURES:2.6.10
#     test: rake testdocker:$ARCHITECTURES:2.6.10
# # 2.6.10
# # | PLATFORM | ARCH   | Working |
# # | OSX     | x86_64 |  |
# # | OSX     | arm64  |  |
# # | Linux   | x86_64 |  |
# # | Linux   | arm64  | ✅ |
# # | Windows | x86_64 |  |
# # | Windows | x86    |  |

BUILD_TEMPLATE: &BUILD_TEMPLATE
  env:
    ARCHITECTURES: $CIRRUS_ARCH
    SANITY_CHECK_OUTPUT_IGNORE: "true"
  env_check_script: |
    echo "CIRRUS_ARCH: $CIRRUS_ARCH"
    echo "PLATFORM: $PLATFORM"
    echo "script: $script"
    echo "NEXT_TAG: $NEXT_TAG"
    echo "ARCHITECTURES: $ARCHITECTURES"
    echo "repo: $repo"
    echo "script: $script"
  build_script: |
    cd $PLATFORM && $script
  test_script: |
    cd $PLATFORM && $test
  # test_script: |
  #   ./shared/test-all-gems.sh $PLATFORM
  upload_script: |
    gh release upload "${NEXT_TAG}" $PLATFORM/*.tar.gz --repo "${REPO}" --clobber
  binary_artifacts:
    path: "$PLATFORM/*.tar.gz"

linux_arm64_docker_builder:
  env:
    CIRRUS_ARCH: arm64
    PLATFORM: linux
    matrix:
      <<: *RUBY_VERSIONS_TASKS
  check_script: uname -a
  <<: *BUILD_TEMPLATE


linux_x64_docker_builder:
  env:
    CIRRUS_ARCH: amd64
    PLATFORM: linux
    matrix:
      <<: *RUBY_VERSIONS_TASKS
  <<: *BUILD_TEMPLATE









PRE_RELEASE_TASK: &PRE_RELEASE_TASK
  script: |
    RELEASE_NOTES=$(git log --pretty=format:"%s" $(git describe --tags --abbrev=0)..HEAD)
    gh release create "${NEXT_TAG}" --prerelease --draft --repo "${REPO}" --title "${NEXT_TAG}" --notes "${RELEASE_NOTES}"

UPLOAD_TASK: &UPLOAD_TASK
  script: |
    gh release upload "${NEXT_TAG}" $PLATFORM/*.tar.gz --repo "${REPO}" --clobber

DOWNLOAD_TASK: &DOWNLOAD_TASK
  script: |
    gh release download  "${NEXT_TAG}" --repo you54f/traveling-ruby -p *$PLATFORM-$CIRRUS_ARCH*

prerelease_task:
  only_if: $CIRRUS_BRANCH == 'next'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    GH_TOKEN: $GITHUB_TOKEN
  <<: *PRE_RELEASE_TASK

upload_task:
  only_if: $CIRRUS_BRANCH == 'next'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    GH_TOKEN: $GITHUB_TOKEN
  <<: *UPLOAD_TASK

# release_task: 
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-ventura-base:latest
#   env:
#     GH_TOKEN: $GITHUB_TOKEN
#   <<: *RELEASE_TASK

download_task:
  only_if: $CIRRUS_BRANCH == 'next'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    GH_TOKEN: $GITHUB_TOKEN
  <<: *DOWNLOAD_TASK
  script: ls