name: MacOS arm64
on:
  push:
    branches: [ main, ci, ruby-3.3, gh_osx_store_runtime ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'
  pull_request:
    branches: [ main, ci, ruby-3.3  ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'

env:
  PKG_DATE: 20240201

jobs:
  make-osx-arm64:
    strategy:
      matrix:
        os: [macos-14]
        ruby-version: [3.1.4,3.2.3,3.3.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.11.0
      #   with:
      #     all_but_latest: true
      - uses: actions/checkout@v3
      - name: download osx arm64 runtime
        run: ./scripts/download-osx-runtime.sh     
        env:
          PLATFORM: osx
          ARCHITECTURES: "arm64"
      - name: build arm64
        run: |
            ls /Applications/Xcode*
            cd osx
            rake stash_conflicting_paths
            rake --trace
            rake unstash_conflicting_paths
            ls
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
          ARCHITECTURES: "arm64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
      # - name: package osx arm64 runtime
      #   run: ./scripts/package-osx-runtime.sh     
      #   env:
      #     PLATFORM: osx
      #     ARCHITECTURES: "arm64"
      # - name: 'Upload Runtime - osx arm64'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: osx-runtime-arm64-gha.tar.gz
      #     path: osx/osx-runtime-arm64.tar.gz
      - name: package gems
        run: ./scripts/package-gems.sh     
        env:
          PLATFORM: osx
      - name: 'Upload Artifact- osx arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-osx-arm64.tar.gz
          path: osx/traveling-ruby*.tar.gz
      - name: test
        run: |
            cd osx
            rake test
        env:
          ARCHITECTURES: "arm64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}