name: MacOS arm64
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'
jobs:
  make-osx-arm64:
    strategy:
      matrix:
        os: [self-hosted]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
      - uses: actions/checkout@v3
      - run: |
            rbenv global 3.3.0
      - name: build arm64
        run: |
            cd osx
            rake stash_conflicting_paths
            rake --trace
            rake unstash_conflicting_paths
            ls
        env:
          DEVELOPER_DIR: /Library/Developer/CommandLineTools
          # CC: /Users/admin/foo/actions-runner/_work/traveling-ruby/traveling-ruby/osx/internal/bin/cc
      - name: 'Upload Artifact - osx arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20240116-3.3.0-osx-arm64.tar.gz
          path: osx/traveling-ruby-20240116-3.3.0-osx-arm64.tar.gz