name: MacOS x86_64
on:
  push:
    branches: [ main, ci, ruby-3.3  ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'
  pull_request:
    branches: [ main, ci, ruby-3.3  ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'

env:
  PKG_DATE: 20240201

jobs:
  make-osx-x86_64:
    strategy:
      matrix:
        os: [macos-12]
        ruby-version: [3.3.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '14.2'
      - name: build x86
        run: |
            cd osx
            rake stash_conflicting_paths
            rake --trace
            rake unstash_conflicting_paths
            ls
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
          ARCHITECTURES: "x86_64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
      - name: 'Upload Artifact- osx x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-osx-x86_64.tar.gz
          path: osx/traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-osx-x86_64.tar.gz