name: MacOS arm64
on:
  push:
    branches: [ main, ci, ruby-3.3  ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'
  pull_request:
    branches: [ main, ci, ruby-3.3  ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'

jobs:
  make-osx-arm64:
    strategy:
      matrix:
        os: [macos-15]
        ruby-version: [3.3.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '14.2'
      - name: build arm64
        run: |
            cd osx
            rake stash_conflicting_paths
            rake --trace
            rake unstash_conflicting_paths
            ls
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
      - name: 'Upload Artifact- osx arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20240201-${{ matrix.ruby-version }}-osx-arm64.tar.gz
          path: osx/traveling-ruby-20240201-${{ matrix.ruby-version }}-osx-arm64.tar.gz