name: Linux - arm64 - build from dockerhub builder
on:
  workflow_dispatch:
  # Broken on GitHub Actions with QEMU

# on:
#   push:
#     branches: [ main, ci, ruby-3.3  ]
#     paths-ignore:
#       - '.circleci/**'
#       - '.cirrus.yml'
#   pull_request:
#     branches: [ main ]
#     paths-ignore:
#       - '.circleci/**'
#       - '.cirrus.yml'

env:
  PKG_DATE: 20240201

jobs:
  make-ubuntu-arm64:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: [3.3.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.11.0
      #   with:
      #     all_but_latest: true
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ matrix.ruby-version }}
      - name: package
        run: |
            docker run --privileged --rm tonistiigi/binfmt --install all
            cd linux
            rake
            ls
        env:
          ARCHITECTURES: "arm64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
      - name: 'Upload Artifact - linux arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-linux-arm64.tar.gz
          path: linux/traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-linux-arm64.tar.gz
      - name: test
        run: |
            cd linux
            rake test_docker
        env:
          ARCHITECTURES: "arm64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}